## @section Git
git:
  ## @param git.repo_url (required) SSH or HTTPS url of the repo to clone
  repo_url: null
  ## @param git.ref branch or tag to check out
  ref: main
  ## @param git.refresh_period how frequently to poll for changes
  refresh_period: 60s
  ## @param git.swagger_path repo-relative path to the target swagger file (OpenAPI spec)
  swagger_path: swagger/swagger.yaml
  ssh:
    ## @param git.ssh.existing_secret_name [string, nullable] if set, configure git-sync to use SSH. This secret should contain a private SSH key and should be created outside this chart
    existing_secret_name: null
    ## @param git.ssh.existing_secret_key [string, nullable] The key of the secret that contains the private SSH key
    existing_secret_key: null

## @section Images
images:
  ## @param images.swagger_ui The swagger-ui image to use
  swagger_ui: "swaggerapi/swagger-ui:v5.17.14"
  ## @param images.git_sync The git-sync image to use
  git_sync: "registry.k8s.io/git-sync/git-sync:v4.0.0"
