apiVersion: v1
kind: Service
metadata:
  name: swagger-stratosphere-v2
  labels:
    app: swagger-stratosphere-v2
spec:
  selector:
    app: swagger-stratosphere-v2
  ports:
    - name: http
      port: 80
      targetPort: http
