name: Build, Test & Release Helm Chart
on:
  push:
    branches:
      - "**"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    # TODO
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v4

      - uses: d3adb5/helm-unittest-action@v2
        with:
          unittest-version: v0.4.2
          charts: charts/swagger-ui-git-sync

      - run: helm lint . -f tests/test-values.yaml
        working-directory: charts/swagger-ui-git-sync
  
  update-readme:
    runs-on: ubuntu-latest
    needs: ["test"]
    # TODO
    if: ${{ false }}
    # if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Install readme-generator
        run: |
          cd /tmp
          curl -LSs "https://github.com/bitnami/readme-generator-for-helm/archive/refs/tags/2.6.1.tar.gz" | tar -xzvf -
          mv readme-generator-for-helm* readmegen
          cd readmegen
          npm install
          npm install pkg
          node_modules/.bin/pkg . -o readmegen

      - uses: actions/checkout@v4

      - name: Update README
        run: /tmp/readmegen/readmegen -v charts/swagger-ui-git-sync/values.yaml -r README.md

      - name: Commit README
        uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          message: Updating README.md [skip ci]
          push: true

  release-chart:
    runs-on: ubuntu-latest
    # TODO needs: ["test"]
    # TODO if: ${{ github.ref == 'refs/heads/main' }}
    # TODO [release-type helm]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # chart-releaser needs a full history
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Release chart
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: "."
          skip_existing: true  # TODO false for SNAPSHOTS
          pages_branch: gh-pages
          config: helm-releaser-config.yaml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
